DO $seed$
DECLARE catalog_id uuid; business_id uuid;
BEGIN
 IF EXISTS(SELECT 1 FROM public.catalogs WHERE slug='boucherie-des-halles') OR EXISTS(SELECT 1 FROM public.ticket_businesses WHERE slug='boucherie-des-halles') THEN RAISE EXCEPTION 'La démo existe déjà : aucune donnée remplacée.'; END IF;
 INSERT INTO public.catalogs(client,catalog_title,slug,accent_color,font_style,cover_image_url,offer_enabled,offer_title,offer_text)
 VALUES('Démonstration Lehnova','Boucherie des Halles','boucherie-des-halles','#872E29','elegante','https://images.pexels.com/photos/5313882/pexels-photo-5313882.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1200&h=800',true,'Le goût des bons moments','Bienvenue chez votre artisan boucher : découvrez nos pièces à griller, nos volailles et nos préparations pour tous les jours. Catalogue de démonstration Lehnova : commerce, tarifs et offres fictifs.') RETURNING id INTO catalog_id;
 INSERT INTO public.catalog_products(catalog_id,name,price,description,photo_url,photo_urls,category,position) VALUES
 (catalog_id,'Duo de steaks à griller','19,90 € le lot','Deux belles pièces à partager, préparées pour le gril.','https://images.pexels.com/photos/5313882/pexels-photo-5313882.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/5313882/pexels-photo-5313882.jpeg?auto=compress&cs=tinysrgb&w=900'],'Promotions du moment',0),
(catalog_id,'Filets de poulet marinés','12,90 € / kg','Une marinade aux herbes pour vos repas de la semaine.','https://images.pexels.com/photos/6107755/pexels-photo-6107755.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/6107755/pexels-photo-6107755.jpeg?auto=compress&cs=tinysrgb&w=900'],'Promotions du moment',1),
(catalog_id,'Pièce de bœuf du week-end','24,90 € / kg','La sélection du boucher, à saisir à feu vif.','https://images.pexels.com/photos/20187072/pexels-photo-20187072.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/20187072/pexels-photo-20187072.jpeg?auto=compress&cs=tinysrgb&w=900'],'Promotions du moment',2),
(catalog_id,'Steak de bœuf','28,90 € / kg','Une pièce généreuse à griller, découpée à la demande.','https://images.pexels.com/photos/7495481/pexels-photo-7495481.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/7495481/pexels-photo-7495481.jpeg?auto=compress&cs=tinysrgb&w=900'],'Le bœuf',3),
(catalog_id,'Rôti de bœuf','26,90 € / kg','Le plaisir d’un déjeuner en famille. Demandez nos conseils de cuisson.','https://images.pexels.com/photos/112781/pexels-photo-112781.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/112781/pexels-photo-112781.jpeg?auto=compress&cs=tinysrgb&w=900'],'Le bœuf',4),
(catalog_id,'Entrecôte','32,90 € / kg','Une pièce persillée pour les amateurs de grillades.','https://images.pexels.com/photos/9541976/pexels-photo-9541976.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/9541976/pexels-photo-9541976.jpeg?auto=compress&cs=tinysrgb&w=900'],'Le bœuf',5),
(catalog_id,'Filets de poulet','14,90 € / kg','Tendres et faciles à cuisiner au quotidien.','https://images.pexels.com/photos/6107734/pexels-photo-6107734.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/6107734/pexels-photo-6107734.jpeg?auto=compress&cs=tinysrgb&w=900'],'Les volailles',6),
(catalog_id,'Émincés de poulet','15,90 € / kg','Prêts à poêler avec vos légumes de saison.','https://images.pexels.com/photos/13422434/pexels-photo-13422434.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/13422434/pexels-photo-13422434.jpeg?auto=compress&cs=tinysrgb&w=900'],'Les volailles',7),
(catalog_id,'Poulet aux épices','16,90 € / kg','Une préparation parfumée, prête à cuire.','https://images.pexels.com/photos/13422436/pexels-photo-13422436.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/13422436/pexels-photo-13422436.jpeg?auto=compress&cs=tinysrgb&w=900'],'Prêts à cuisiner',8),
(catalog_id,'Steak aux herbes','29,90 € / kg','Romarin, thym et une belle pièce de viande.','https://images.pexels.com/photos/5313882/pexels-photo-5313882.jpeg?auto=compress&cs=tinysrgb&w=900',ARRAY['https://images.pexels.com/photos/5313882/pexels-photo-5313882.jpeg?auto=compress&cs=tinysrgb&w=900'],'Prêts à cuisiner',9);
 INSERT INTO public.ticket_businesses(name,slug,is_active,offers_url,offer_previews,public_screen_enabled)
 VALUES('Boucherie des Halles · Démo','boucherie-des-halles',true,'https://lehnova.fr/catalogue/boucherie-des-halles#promotions-du-moment','[{"title":"Duo de steaks à griller","detail":"19,90 € le lot","image_url":"https://images.pexels.com/photos/5313882/pexels-photo-5313882.jpeg?auto=compress&cs=tinysrgb&w=900","url":null},{"title":"Filets de poulet marinés","detail":"12,90 € / kg","image_url":"https://images.pexels.com/photos/6107755/pexels-photo-6107755.jpeg?auto=compress&cs=tinysrgb&w=900","url":null},{"title":"Pièce de bœuf du week-end","detail":"24,90 € / kg","image_url":"https://images.pexels.com/photos/20187072/pexels-photo-20187072.jpeg?auto=compress&cs=tinysrgb&w=900","url":null}]'::jsonb,true) RETURNING id INTO business_id;
 INSERT INTO public.ticket_queues(business_id,is_open,queue_mode,estimated_minutes_per_client) VALUES(business_id,true,'tickets',3);
END $seed$;
