"use client";
import {Suspense,useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {OfferFields} from '../../ticket/OfferEditor';

function TicketOffersAdminContent(){
 const search=useSearchParams();const id=search.get('id');
 const [business,setBusiness]=useState(null),[url,setUrl]=useState(''),[offers,setOffers]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!id){setMessage('Commerce Ticket manquant.');setLoading(false);return;}const controller=new AbortController();fetch('/api/admin/tickets',{cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);const list=Array.isArray(data)?data:(data.businesses||data.data||[]);const found=list.find(item=>String(item.id)===String(id));if(!found)throw new Error('Commerce introuvable.');setBusiness(found);setUrl(found.offers_url||'');setOffers(Array.isArray(found.offer_previews)?found.offer_previews:[]);}).catch(e=>{if(e.name!=='AbortError')setMessage(e.message||'Chargement impossible.');}).finally(()=>setLoading(false));return()=>controller.abort();},[id]);
 async function save(){setBusy(true);setMessage('');try{const r=await fetch(`/api/admin/tickets/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({offers_url:url,offer_previews:offers})});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage('Offres enregistrées. Elles sont maintenant visibles sur le Ticket.');}catch(e){setMessage(e.message||'Enregistrement impossible.');}finally{setBusy(false);}}
 const input={width:'100%',boxSizing:'border-box',padding:12,fontSize:16,border:'1px solid #D8CCAB',borderRadius:8};
 return <main style={{minHeight:'100vh',background:'#F7F3EC',padding:'24px 14px',color:'#49382D'}}><div style={{maxWidth:760,margin:'0 auto'}}><a href="/admin" style={{color:'#5B4636',fontWeight:700,textDecoration:'none'}}>← Retour à l’admin</a><section style={{marginTop:16,background:'#fff',borderRadius:18,padding:20,boxShadow:'0 8px 24px rgba(80,60,40,.08)'}}><p style={{margin:'0 0 5px',fontSize:12,fontWeight:800,color:'#9B775A'}}>LEHNOVA TICKET</p><h1 style={{margin:'0 0 6px',fontSize:26}}>Gérer les offres</h1>{business&&<p style={{margin:'0 0 20px',color:'#765F4E'}}>{business.name}</p>}{loading?<p>Chargement…</p>:business?<><label style={{display:'grid',gap:7,fontWeight:700}}>Lien de la page complète des offres<input type="url" placeholder="https://lehnova.fr/..." maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)} style={input}/></label><OfferFields offers={offers} onChange={setOffers} disabled={busy}/><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button type="button" disabled={busy} onClick={save} style={{padding:'12px 18px',border:0,borderRadius:10,background:'#5B4636',color:'#fff',fontWeight:800}}>{busy?'Enregistrement…':'Enregistrer les offres'}</button>{business.slug&&<a href={`/ticket/${business.slug}`} target="_blank" rel="noreferrer" style={{padding:'12px 18px',border:'1px solid #D8CCAB',borderRadius:10,color:'#5B4636',fontWeight:700,textDecoration:'none'}}>Voir le Ticket</a>}</div></>:null}<p role="status" style={{marginTop:16,color:message.startsWith('Offres enregistrées')?'#287A45':'#A43B32'}}>{message}</p></section></div></main>;
}

export default function TicketOffersAdminPage(){
 return <Suspense fallback={<main style={{minHeight:'100vh',background:'#F7F3EC',padding:24}}>Chargement…</main>}><TicketOffersAdminContent/></Suspense>;
}
