"use client";
import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { supabase } from "../../../lib/supabaseClient";
import { ticketBase, ticketColors } from "../../ticket/ticketStyles";

export default function AttentePublic(){
 const {slug}=useParams(); const router=useRouter(); const [state,setState]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!supabase||!slug)return;try{const {data:rows,error:rpcError}=await supabase.rpc("ticket_public_state",{p_slug:slug,p_resume_token:null});if(rpcError)throw rpcError;const base=Array.isArray(rows)?rows[0]:rows;if(!base)throw new Error("Commerce introuvable.");const {data:queue,error:queueError}=await supabase.from("ticket_queues").select("queue_mode, manual_waiting_count, estimated_minutes_per_client, public_wait_display_enabled").eq("business_id",base.business_id).single();if(queueError)throw queueError;if(queue.queue_mode!=="manual"){router.replace(`/ticket/${slug}`);return;}setState({...base,...queue});setError("");}catch(err){setError(err.message||"Chargement impossible.");}finally{setLoading(false);}},[router,slug]);
 useEffect(()=>{load();},[load]);
 useEffect(()=>{if(!supabase||!state?.business_id)return;const channel=supabase.channel(`attente-public-${state.business_id}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"ticket_queues",filter:`business_id=eq.${state.business_id}`},load).subscribe();const timer=window.setInterval(load,15000);return()=>{supabase.removeChannel(channel);window.clearInterval(timer);};},[load,state?.business_id]);
 const count=state?.manual_waiting_count||0; const estimate=state?.estimated_minutes_per_client?count*state.estimated_minutes_per_client:null;
 return <main style={styles.page}><section style={styles.card}><p style={styles.brand}>LEHNOVA ATTENTE</p><h1 style={styles.business}>{state?.business_name||"Votre commerce"}</h1>{loading?<p style={styles.message}>Chargement…</p>:error?<p style={styles.error}>{error}</p>:state.public_wait_display_enabled===false?<div style={styles.center}><p style={styles.message}>L’attente n’est pas affichée actuellement.</p></div>:<div style={styles.center}><p style={styles.label}>ATTENTE ACTUELLE</p><div style={styles.number}>{count}</div><p style={styles.people}>{count===1?"personne en attente":"personnes en attente"}</p>{estimate!==null&&<div style={styles.estimate}>Environ {estimate} minutes d’attente</div>}</div>}</section></main>;
}
const styles={page:{...ticketBase,display:"grid",placeItems:"center",padding:"20px 14px"},card:{width:"100%",maxWidth:440,minHeight:620,background:ticketColors.paper,border:`1px solid ${ticketColors.border}`,borderRadius:28,padding:"28px 22px 20px",display:"flex",flexDirection:"column",boxShadow:"0 22px 60px -40px rgba(34,29,24,.4)"},brand:{margin:0,color:ticketColors.accent,fontSize:12,fontWeight:800,letterSpacing:".18em",textAlign:"center"},business:{margin:"8px 0 30px",fontSize:20,textAlign:"center"},center:{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",textAlign:"center"},label:{margin:0,color:ticketColors.gold,fontSize:13,fontWeight:800,letterSpacing:".16em"},number:{margin:"14px 0 4px",fontSize:112,lineHeight:1,fontWeight:900},people:{margin:0,color:ticketColors.muted,fontSize:19,fontWeight:700},estimate:{marginTop:22,padding:"16px 20px",borderRadius:15,background:ticketColors.background,color:ticketColors.accent,fontSize:18,fontWeight:800},message:{color:ticketColors.muted,textAlign:"center",lineHeight:1.55},error:{color:ticketColors.accent,textAlign:"center"}};

