"use client";
import { useState } from "react";
function photo(p){return p.photo_urls?.[0] || p.photo_url || "";}
export default function ShowroomView({catalog,products,transformations=[]}){
 const [selected,setSelected]=useState(null);
 const accent=catalog.accent_color||"#85745E";
 const groups=[...new Set(products.map(p=>p.category||"Collections"))];
 return <main className="sr">
 <style>{`
 .sr{max-width:980px;margin:0 auto;min-height:100vh;background:#fbfaf7;color:#2e2b28;font-family:Arial,sans-serif}.sr *{box-sizing:border-box}.sr .hero{min-height:490px;background-color:#333;background-size:cover;background-position:center;display:flex;flex-direction:column;justify-content:space-between;padding:28px;color:#fff}.sr .ey{font-size:11px;letter-spacing:3px;text-transform:uppercase;font-weight:bold}.sr h1{font:normal clamp(39px,7vw,67px) Georgia,serif;line-height:1.07;max-width:620px;margin:12px 0}.sr h2{font:normal 36px Georgia,serif;margin:10px 0 18px}.sr p{line-height:1.65}.sr .cta{display:inline-block;background:var(--accent);color:white;text-decoration:none;padding:14px 21px;border-radius:5px;font-weight:bold}.sr section.body{padding:42px 22px}.sr .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.sr .item{background:#fff;border:1px solid #e4ded4;border-radius:8px;overflow:hidden;text-align:left;cursor:pointer;color:inherit}.sr .item img{width:100%;aspect-ratio:4/3;object-fit:cover}.sr .desc{padding:15px}.sr .desc h3{font:normal 21px Georgia,serif;margin:7px 0}.sr small{color:#8c795f;letter-spacing:1px}.sr .pictures{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.sr .pictures img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:8px}.sr .foot{background:#2e2b28;color:#fff;text-align:center;padding:44px 20px}.sr .modal{position:fixed;z-index:90;inset:0;background:#000b;display:flex;align-items:center;justify-content:center;padding:18px}.sr .modalContent{background:#fff;max-width:540px;max-height:92vh;overflow:auto;width:100%;border-radius:12px;padding:18px}.sr .modalContent img{width:100%;max-height:430px;object-fit:contain}.sr .close{float:right;border:0;background:#eee;padding:8px 14px;border-radius:5px;cursor:pointer}@media(max-width:540px){.sr .grid{gap:9px}.sr .desc{padding:10px}.sr .desc h3{font-size:17px}.sr h2{font-size:30px}.sr .hero{min-height:440px;padding:21px}}
 `}</style>
 <div style={{"--accent":accent}}>
 <section className="hero" style={{backgroundImage:catalog.cover_image_url?`linear-gradient(180deg,#15120f55,#15120fd0),url("${catalog.cover_image_url}")`:"linear-gradient(135deg,#34312d,#8a7865)"}}>
 <div className="ey">{catalog.client}</div><div><div className="ey">SHOWROOM NUMÉRIQUE</div><h1>{catalog.catalog_title}</h1><p>Découvrez nos collections, trouvez l’inspiration et préparez votre projet.</p><a className="cta" href="#collections">Découvrir les collections ↓</a></div></section>
 {catalog.offer_enabled&&catalog.offer_title&&<section className="body" style={{background:"#eee8dd"}}><div className="ey">EN CE MOMENT</div><h2>{catalog.offer_title}</h2><p>{catalog.offer_text}</p></section>}
 <section id="collections" className="body"><div className="ey">NOS UNIVERS</div><h2>Les collections</h2><p>Explorez les matières, les coloris et les finitions.</p>{products.length===0?<p>Les premières collections arrivent bientôt.</p>:groups.map(group=><div key={group} style={{marginTop:30}}><h2 style={{fontSize:25}}>{group}</h2><div className="grid">{products.filter(p=>(p.category||"Collections")===group).map(p=><button className="item" key={p.id} onClick={()=>setSelected(p)}>{photo(p)&&<img src={photo(p)} alt={p.name} loading="lazy"/>}<div className="desc"><small>{group.toUpperCase()}</small><h3>{p.name}</h3>{p.price&&<strong>{p.price}</strong>}</div></button>)}</div></div>)}</section>
 {catalog.portfolio_photo_urls?.length>0&&<section className="body" style={{background:"#ede8df"}}><div className="ey">INSPIRATIONS</div><h2>Nos réalisations</h2><div className="pictures">{catalog.portfolio_photo_urls.map((url,i)=><img key={i} src={url} alt={`Réalisation ${i+1}`} loading="lazy"/>)}</div></section>}
 {transformations.length>0&&<section className="body"><div className="ey">AVANT / APRÈS</div><h2>Nos transformations</h2><div className="grid">{transformations.map(t=><div key={t.id} className="item" style={{cursor:"default"}}><div className="pictures">{t.before_url&&<img src={t.before_url} alt="Avant"/>}{t.after_url&&<img src={t.after_url} alt="Après"/>}</div><div className="desc">{t.label}</div></div>)}</div></section>}
 <section className="foot"><div className="ey">UN PROJET ?</div><h2>Parlons de votre projet</h2><p>Contactez-nous pour découvrir nos collections ou demander un devis.</p><div style={{display:"flex",gap:10,justifyContent:"center",flexWrap:"wrap"}}>{catalog.instagram_url&&<a className="cta" href={catalog.instagram_url} target="_blank" rel="noreferrer">Instagram</a>}{catalog.facebook_url&&<a className="cta" href={catalog.facebook_url} target="_blank" rel="noreferrer">Facebook</a>}{catalog.google_review_url&&<a className="cta" href={catalog.google_review_url} target="_blank" rel="noreferrer">Avis Google</a>}</div><p style={{fontSize:12,opacity:.6}}>Showroom créé avec Lehnova</p></section>
 {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="modalContent" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>Fermer ✕</button><h2>{selected.name}</h2>{(selected.photo_urls?.length?selected.photo_urls:[selected.photo_url]).filter(Boolean).map((url,i)=><img src={url} alt={selected.name} key={i}/>)}<p>{selected.description}</p><strong>{selected.price}</strong></div></div>}
 </div></main>;
}