"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { changeWaitingCount, getAttenteQueue, getMerchantSession, saveAverageMinutes, setPublicDisplay, signOutMerchant, subscribeToAttente } from "../../../lib/attente/attenteApi";
import { ticketBase, ticketColors } from "../../ticket/ticketStyles";

export default function AttenteDashboard(){
 const router=useRouter(); const [queue,setQueue]=useState(null); const [minutes,setMinutes]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const load=useCallback(async()=>{try{const data=await getAttenteQueue();setQueue(data);setMinutes(data.estimated_minutes_per_client??"");setError("");}catch(err){setError(err.message||"Chargement impossible.");}finally{setLoading(false);}},[]);
 useEffect(()=>{getMerchantSession().then(s=>{if(!s?.authenticated||s.mode!=="manual")router.replace("/attente/connexion");else load();}).catch(()=>router.replace("/attente/connexion"));},[load,router]);
 useEffect(()=>queue?.business_id?subscribeToAttente(queue.business_id,load):undefined,[queue?.business_id,load]);
 async function run(fn){if(busy)return;setBusy(true);try{await fn();await load();}catch(err){setError(err.message||"Action impossible.");}finally{setBusy(false);}}
 async function logout(){await signOutMerchant().catch(()=>{});router.replace("/attente/connexion");}
 if(loading)return <main style={{...styles.page,placeItems:"center"}}>Chargement…</main>;
 return <main style={styles.page}><section style={styles.shell}><header style={styles.header}><div><p style={styles.brand}>LEHNOVA ATTENTE</p><h1 style={styles.business}>{queue?.business_name||"Espace commerçant"}</h1></div><button onClick={logout} style={styles.logout}>Déconnexion</button></header>{queue&&<div style={styles.panel}><p style={styles.label}>PERSONNES EN ATTENTE</p><div style={styles.counter}><button disabled={busy||queue.manual_waiting_count===0} onClick={()=>run(()=>changeWaitingCount(-1))} style={styles.counterButton}>−</button><strong style={styles.number}>{queue.manual_waiting_count||0}</strong><button disabled={busy} onClick={()=>run(()=>changeWaitingCount(1))} style={styles.counterButton}>+</button></div><div style={styles.estimate}><label style={styles.estimateLabel}>Temps moyen par client</label><div style={styles.row}><input type="number" min="1" max="180" value={minutes} onChange={e=>setMinutes(e.target.value)} placeholder="10" style={styles.input}/><span>minutes</span><button disabled={busy} onClick={()=>run(()=>saveAverageMinutes(minutes===""?null:Number(minutes)))} style={styles.save}>ENREGISTRER</button></div>{minutes&&<p style={styles.result}>Attente calculée : environ {(queue.manual_waiting_count||0)*Number(minutes)} minutes</p>}</div><button disabled={busy} onClick={()=>run(()=>setPublicDisplay(!queue.public_wait_display_enabled))} style={queue.public_wait_display_enabled?styles.on:styles.off}>{queue.public_wait_display_enabled?"● AFFICHAGE PUBLIC ACTIVÉ":"○ AFFICHAGE PUBLIC MASQUÉ"}</button></div>}{error&&<p style={styles.error}>{error}</p>}</section></main>;
}
const styles={page:{...ticketBase,display:"grid",padding:"22px 16px"},shell:{width:"100%",maxWidth:700,margin:"0 auto"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,marginBottom:24},brand:{margin:0,color:ticketColors.accent,fontSize:11,fontWeight:800,letterSpacing:".18em"},business:{margin:"5px 0 0",fontSize:22},logout:{border:0,background:"transparent",color:ticketColors.muted,fontWeight:650},panel:{background:"#FFF",border:`1px solid ${ticketColors.border}`,borderRadius:28,padding:"34px 24px",textAlign:"center"},label:{margin:0,color:ticketColors.gold,fontSize:14,fontWeight:800,letterSpacing:".16em"},counter:{display:"flex",justifyContent:"center",alignItems:"center",gap:28,margin:"22px 0 32px"},counterButton:{width:72,height:72,border:`2px solid ${ticketColors.ink}`,borderRadius:"50%",background:"#FFF",fontSize:38},number:{minWidth:110,fontSize:88,lineHeight:1},estimate:{padding:18,borderRadius:16,background:ticketColors.background,textAlign:"left"},estimateLabel:{display:"block",marginBottom:10,fontWeight:800},row:{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"},input:{width:90,minHeight:44,padding:10,border:`1px solid ${ticketColors.border}`,borderRadius:10,fontSize:17},save:{minHeight:44,marginLeft:"auto",padding:"0 14px",border:0,borderRadius:10,background:ticketColors.ink,color:"#FFF",fontWeight:800},result:{margin:"12px 0 0",color:ticketColors.accent,fontWeight:750},on:{width:"100%",minHeight:52,marginTop:16,border:`1px solid ${ticketColors.success}`,borderRadius:14,background:"#FFF",color:ticketColors.success,fontWeight:800},off:{width:"100%",minHeight:52,marginTop:16,border:`1px solid ${ticketColors.muted}`,borderRadius:14,background:"#FFF",color:ticketColors.muted,fontWeight:800},error:{color:ticketColors.accent,textAlign:"center"}};

