"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabaseClient";
const SLUG="sarah-karim-demo";
export default function DemoFil(){
 const [ev,setEv]=useState(null),[msgs,setMsgs]=useState([]),[polls,setPolls]=useState([]),[words,setWords]=useState([]),[riddles,setRiddles]=useState([]),[word,setWord]=useState(""),[ri,setRi]=useState(0),[answer,setAnswer]=useState(""),[result,setResult]=useState(null),[song,setSong]=useState(""),[artist,setArtist]=useState("");
 async function load(){const {data:e}=await supabase.from("events").select("*").eq("slug",SLUG).single();if(!e)return;setEv(e);const [m,p,w,r]=await Promise.all([supabase.from("messages").select("*").eq("event_id",e.id).order("created_at",{ascending:false}),supabase.from("poll_questions").select("*").eq("event_id",e.id).order("position"),supabase.from("word_cloud_entries").select("*").eq("event_id",e.id),supabase.from("event_riddles").select("*").eq("event_id",e.id).order("position")]);setMsgs(m.data||[]);setPolls(p.data||[]);setWords(w.data||[]);setRiddles(r.data||[])}
 useEffect(()=>{load()},[]);
 const cloud=useMemo(()=>{const c={};words.forEach(x=>{let w=(x.word||"").trim().toLowerCase();if(w)c[w]=(c[w]||0)+1});return Object.entries(c).sort((a,b)=>b[1]-a[1])},[words]);
 const jump=id=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});
 async function addWord(e){e.preventDefault();if(!word.trim())return;await supabase.from("word_cloud_entries").insert({event_id:ev.id,word:word.trim().slice(0,28)});setWord("");load()}
 async function sendSong(e){e.preventDefault();if(!song.trim())return;await supabase.from("playlist_requests").insert({event_id:ev.id,song_title:song.trim(),artist:artist.trim()||null});setSong("");setArtist("")}
 function norm(s){return(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g,"").trim()}
 function check(e){e.preventDefault();const r=riddles[ri];if(!r)return;setResult(norm(answer)===norm(r.answer)?"yes":"no")}
 if(!ev)return <main style={s.loading}>Chargement…</main>;
 const r=riddles[ri];
 return <main style={s.page}><div style={s.app}>
  <header style={s.head}><div><div style={s.brand}>LE FIL</div><h1 style={s.title}>Sarah <i style={s.and}>&</i> Karim</h1><p style={s.date}>Notre soirée · 15 août 2026</p></div><div style={s.avatar}>S&K</div></header>
  <nav style={s.nav}>{[["quiz","Quiz"],["dj","Musique"],["riddle","Devinettes"],["souvenir","Souvenir"],["fund","Cagnotte"],["cloud","Nuage de mots"]].map(([id,t])=><button key={id} onClick={()=>jump(id)} style={s.navBtn}>{t}</button>)}</nav>

  <section id="quiz" style={s.block}><Label>Petit quiz</Label><h2 style={s.h2}>On commence par vous tester un peu…</h2>{polls[0]&&<div style={s.card}><p style={s.question}>{polls[0].question}</p><div style={s.options}>{(polls[0].options||[]).map((o,i)=><button key={i} style={s.option}>{o}</button>)}</div></div>}</section>

  {ev.playlist_enabled&&<section id="dj" style={s.block}><Label>Pour le DJ</Label><h2 style={s.h2}>Un titre qui doit passer ce soir ?</h2><p style={s.sub}>Glissez votre morceau ici, il arrive directement dans les demandes du DJ.</p><form onSubmit={sendSong} style={s.card}><input style={s.input} placeholder="Titre de la chanson" value={song} onChange={e=>setSong(e.target.value)}/><input style={s.input} placeholder="Artiste" value={artist} onChange={e=>setArtist(e.target.value)}/><button style={s.primary}>Envoyer la demande ♫</button></form></section>}

  {ev.riddles_enabled&&r&&<section id="riddle" style={s.block}><Label>Devinettes</Label><div style={s.row}><h2 style={s.h2}>À vous de jouer</h2><span style={s.counter}>{ri+1}/{riddles.length}</span></div><div style={s.card}><p style={s.question}>{r.question}</p><form onSubmit={check} style={s.answerRow}><input style={s.input} placeholder="Votre réponse" value={answer} onChange={e=>{setAnswer(e.target.value);setResult(null)}}/><button style={s.square}>→</button></form>{result==="yes"&&<p style={s.ok}>Bien joué ✦</p>}{result==="no"&&<p style={s.no}>Presque… Indice : {r.hint}</p>}{result&&<button style={s.next} onClick={()=>{setRi((ri+1)%riddles.length);setAnswer("");setResult(null)}}>Suivante →</button>}</div></section>}

  <section id="souvenir" style={s.memory}><Label>Pour les mariés</Label><h2 style={s.memoryTitle}>Laissez quelque chose<br/>qui restera.</h2><p style={s.memorySub}>Un instant, quelques mots ou simplement votre voix.</p><div style={s.memoryActions}><button style={s.memoryBtn}><b>Photo ou vidéo</b><span>Ajouter un moment</span><em>＋</em></button><button style={s.memoryBtn}><b>Écrire un mot</b><span>Quelques lignes pour eux</span><em>＋</em></button><button style={s.memoryBtn}><b>Message vocal</b><span>Votre voix en souvenir</span><em>＋</em></button></div></section>

  <section style={s.feed}><div style={s.feedTop}><div><Label>Les souvenirs</Label><h2 style={s.h2}>Le Fil de la soirée</h2></div><span style={s.live}>● en direct</span></div>{msgs.slice(0,6).map(m=><article key={m.id} style={s.post}>{m.photo_url&&<img src={m.photo_url} style={s.photo}/>}<div style={s.postBody}><div style={s.meta}><b>{m.name||"Invité"}</b><span>♡ {m.likes_count||0}</span></div>{m.message&&<p style={s.message}>{m.message}</p>}{m.audio_url&&<audio controls src={m.audio_url} style={{width:"100%"}}/>}</div></article>)}</section>

  <section id="fund" style={s.block}><Label>Cagnotte</Label><div style={s.fund}><div><h2 style={s.h2}>Pour leur prochaine aventure</h2><p style={s.sub}>Une petite attention pour accompagner la suite de leur histoire.</p></div><button style={s.fundBtn}>Participer ↗</button></div></section>

  {ev.word_cloud_enabled&&<section id="cloud" style={{...s.block,paddingBottom:100}}><Label>Un dernier mot</Label><h2 style={s.h2}>Comment décririez-vous Sarah & Karim ?</h2><div style={s.cloud}>{cloud.map(([w,n],i)=><span key={w} style={{fontSize:Math.min(31,16+n*4+(i===0?3:0)),opacity:Math.max(.55,1-i*.05)}}>{w}</span>)}</div><form onSubmit={addWord} style={s.answerRow}><input style={s.input} placeholder="Un mot…" value={word} onChange={e=>setWord(e.target.value)}/><button style={s.square}>＋</button></form></section>}
 </div></main>
}
function Label({children}){return <div style={s.label}>{children}</div>}
const s={
 page:{minHeight:"100vh",background:"#eeeae4",color:"#292522",fontFamily:"Arial,Helvetica,sans-serif"},loading:{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f5f1eb"},app:{width:"100%",maxWidth:760,margin:"0 auto",background:"#f9f7f3",minHeight:"100vh",boxShadow:"0 0 50px rgba(45,35,25,.08)"},
 head:{padding:"34px 24px 20px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,borderBottom:"1px solid #e6dfd6"},brand:{fontSize:10,fontWeight:800,letterSpacing:".28em",color:"#a68458",marginBottom:9},title:{margin:0,fontFamily:"'Baskerville','Times New Roman',serif",fontSize:"clamp(37px,8vw,56px)",fontWeight:400,letterSpacing:"-.045em",lineHeight:.95},and:{fontWeight:400,color:"#b08c5b",fontSize:".75em"},date:{margin:"10px 0 0",fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:13,color:"#8a8178"},avatar:{width:48,height:48,borderRadius:"50%",border:"1px solid #cdbb9f",display:"grid",placeItems:"center",fontFamily:"Georgia,serif",fontSize:13,color:"#8a6942",flexShrink:0},
 nav:{position:"sticky",top:0,zIndex:20,display:"flex",gap:8,overflowX:"auto",padding:"11px 14px",background:"rgba(249,247,243,.96)",backdropFilter:"blur(10px)",borderBottom:"1px solid #e6dfd6",scrollbarWidth:"none"},navBtn:{whiteSpace:"nowrap",border:"1px solid #ded3c5",borderRadius:999,background:"#fff",padding:"9px 13px",fontSize:12,color:"#4d453e",cursor:"pointer"},
 block:{padding:"38px 22px",borderBottom:"1px solid #e6dfd6",scrollMarginTop:65},label:{textTransform:"uppercase",letterSpacing:".2em",fontSize:9,fontWeight:800,color:"#a17d4d",marginBottom:8},h2:{fontFamily:"'Baskerville','Times New Roman',serif",fontSize:"clamp(27px,5vw,35px)",lineHeight:1.08,fontWeight:400,letterSpacing:"-.025em",margin:"0 0 14px"},sub:{fontFamily:"Georgia,serif",fontSize:14,lineHeight:1.6,color:"#81776e",margin:"0 0 18px"},card:{background:"#fff",border:"1px solid #e1d8cc",borderRadius:18,padding:18,display:"grid",gap:10,boxShadow:"0 7px 22px rgba(65,50,35,.035)"},question:{fontFamily:"Georgia,serif",fontSize:19,lineHeight:1.45,margin:"2px 0 8px"},options:{display:"grid",gap:8},option:{border:"1px solid #dfd5c8",borderRadius:12,background:"#faf8f5",padding:"13px 14px",textAlign:"left",fontSize:14,color:"#39332e"},input:{width:"100%",boxSizing:"border-box",border:"1px solid #ded4c8",borderRadius:12,background:"#fbfaf8",padding:"13px 14px",fontSize:14,outline:"none"},primary:{border:0,borderRadius:12,background:"#332c27",color:"#fff",padding:14,fontWeight:700,fontSize:13},row:{display:"flex",justifyContent:"space-between",alignItems:"start",gap:12},counter:{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:13,color:"#a07b4d",paddingTop:7},answerRow:{display:"flex",gap:8},square:{width:48,flex:"0 0 48px",border:0,borderRadius:12,background:"#a98555",color:"#fff",fontSize:20},ok:{fontSize:13,color:"#52745a",fontWeight:700,margin:"4px 0 0"},no:{fontFamily:"Georgia,serif",fontStyle:"italic",fontSize:13,color:"#9b6659",margin:"4px 0 0"},next:{border:0,background:"none",textAlign:"left",padding:"5px 0 0",fontWeight:700,color:"#8d6a40"},
 memory:{padding:"44px 22px",background:"#302a26",color:"#fff",scrollMarginTop:65},memoryTitle:{fontFamily:"'Baskerville','Times New Roman',serif",fontSize:"clamp(35px,7vw,48px)",fontWeight:400,lineHeight:1.02,letterSpacing:"-.035em",margin:"0 0 13px"},memorySub:{fontFamily:"Georgia,serif",fontStyle:"italic",color:"#cfc4b9",fontSize:14,margin:"0 0 24px"},memoryActions:{display:"grid",gap:1,background:"#554a42",border:"1px solid #554a42",borderRadius:16,overflow:"hidden"},memoryBtn:{position:"relative",border:0,background:"#39322d",color:"#fff",padding:"17px 50px 17px 17px",display:"flex",flexDirection:"column",textAlign:"left",gap:4},memoryBtnSpan:{},
 feed:{padding:"38px 14px",borderBottom:"1px solid #e6dfd6"},feedTop:{padding:"0 8px",display:"flex",justifyContent:"space-between",alignItems:"end",gap:12,marginBottom:18},live:{fontSize:10,color:"#9b7950",whiteSpace:"nowrap",paddingBottom:17},post:{background:"#fff",border:"1px solid #e2d9ce",borderRadius:18,overflow:"hidden",marginBottom:14},photo:{display:"block",width:"100%",height:"auto",maxHeight:620,objectFit:"cover"},postBody:{padding:16},meta:{display:"flex",justifyContent:"space-between",fontSize:12,color:"#716860"},message:{fontFamily:"Georgia,serif",fontSize:17,lineHeight:1.55,margin:"12px 0 2px",color:"#403934"},
 fund:{display:"flex",alignItems:"end",justifyContent:"space-between",gap:16},fundBtn:{whiteSpace:"nowrap",border:"1px solid #b99d78",borderRadius:999,background:"transparent",padding:"11px 14px",color:"#765a38"},cloud:{minHeight:170,display:"flex",alignItems:"center",justifyContent:"center",flexWrap:"wrap",gap:"10px 17px",fontFamily:"'Baskerville','Times New Roman',serif",color:"#86673f",padding:"18px 8px",marginBottom:12}
};